spring:
  application:
    name: product-service
  datasource:
    url: jdbc:mysql://localhost:3306/productDb?createDatabaseIfNotExist=true&useSSL=false
    username: root
    password: testing12345
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        enabled: true
        service-name: product-service
        healthCheckPath: /actuator/health
        healthCheckInterval: 30s

server:
  port: 8092
